name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "First Action - 1st Job"
        run: echo "Hello World"
      - name: "Second Action - 1st Job"
        run: |
          echo "You created your first workflow"
          echo "Congratulations"
  second-job:
    name: "Installing NodeJS environment"
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: "Verifying NodeJS version"
        run: node --version
      - name: "Definition of NodeJS version 22.15.0"
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - name: "Verifying NodeJS version again after manual installation"
        run: node --version
